### PR TITLE
fix npe when inventory object is nil

### LINKED ISSUE #3902: NPE while getting Kustomization inventory
**given** this kustomization 
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  creationTimestamp: "2023-07-31T15:05:53Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: rbac-secrets-good-practices
  namespace: flux-system
  resourceVersion: "9437086"
  uid: f3780853-bf47-4a3b-b5e3-f029623e8595
spec:
  force: false
  interval: 1m0s
  path: ./goodpractices/kubernetes/rbac/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: policy-library
status:
  conditions:
  - lastTransitionTime: "2023-07-31T15:05:54Z"
    message: Source is not ready, artifact not found
    observedGeneration: 1
    reason: ArtifactFailed
    status: "False"
    type: Ready
  observedGeneration: -1
```
**when** getting inventory 
**then** npe is thrown due to kustomization without enteries
```
2023/07/31 15:09:35 http: panic serving 127.0.0.1:56444: runtime error: invalid memory address or nil pointer dereference
goroutine 23912 [running]:
net/http.(*conn).serve.func1()
	/opt/homebrew/Cellar/go/1.20.2/libexec/src/net/http/server.go:1854 +0xbf
panic({0x346fca0, 0x61e4e10})
	/opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/panic.go:890 +0x263
github.com/weaveworks/weave-gitops/core/server.(*coreServer).getKustomizationInventory(0xc001204780, {0x427ff68?, 0xc002826780}, {0xc0010e8068, 0xa}, {0x4295480, 0xc000293490}, {0xc0010e8017, 0x1b}, {0xc0010e803d, ...}, ...)
	/github.com/weaveworks/weave-gitops-enterprise/vendor/github.com/weaveworks/weave-gitops/core/server/inventory.go:74 +0x178
github.com/weaveworks/weave-gitops/core/server.(*coreServer).GetInventory(0xc001204780, {0x427ff68, 0xc002826780}, 0xc005c80000)
```

### PR DESCRIPTION
**Pull request by chanwit**
Fixes #3902

### CODE REVIEW

**Review by enekofb — COMMENTED** [review]
we could add a test case [here](https://github.com/weaveworks/weave-gitops/blob/main/core/server/inventory_test.go#L87) for the scenario we are trying to handle 

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  creationTimestamp: "2023-07-31T15:05:53Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: rbac-secrets-good-practices
  namespace: flux-system
  resourceVersion: "9437086"
  uid: f3780853-bf47-4a3b-b5e3-f029623e8595
spec:
  force: false
  interval: 1m0s
  path: ./goodpractices/kubernetes/rbac/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: policy-library
status:
  conditions:
  - lastTransitionTime: "2023-07-31T15:05:54Z"
    message: Source is not ready, artifact not found
    observedGeneration: 1
    reason: ArtifactFailed
    status: "False"
    type: Ready
  observedGeneration: -1
```
added the example also to the ticket

**Review by enekofb — APPROVED** [review]

File: core/server/inventory.go [hunk 1]
```diff
@@ -71,6 +71,10 @@ func (cs *coreServer) getKustomizationInventory(ctx context.Context, clusterName
 		return nil, fmt.Errorf("failed to get kustomization: %w", err)
 	}
 
+	if kust.Status.Inventory == nil {
+		return []*pb.InventoryEntry{}, nil
+	}
```
Comment (bigkevmcd) [inline core/server/inventory.go:76]: I think this can return `nil` here?

The PB generates `omitempty` so either way the result would be the same?

https://github.com/weaveworks/weave-gitops/blob/main/pkg/api/core/core.pb.go#L114

If you're not sure if this results in the same thing, https://go.dev/play/p/Av1DA7zf9QF

**Review by bigkevmcd — CHANGES_REQUESTED** [review]

**Comment by bigkevmcd** [comment]
@chanwit are you going to address these issues? if not, I'll happily close this and open a new PR to do it.

**Comment by chanwit** [comment]
I'll continue this week. Sorry I am currently having a technical issue with my box.

**Review by bigkevmcd — APPROVED** [review]
