### PR TITLE
Fix Github auth when running from `wego ui run`

### LINKED ISSUE #812: Github auth flow does not work when using `wego ui run`
**Describe the bug**

**Affects versions**
0.3.0

**To Reproduce**
1. `wego ui run`
2. Click "Authenticate with Github" in the commits section of the application detail

**Expected behavior**
Auth flow completes and commits are shown

**Actual Behavior**
Auth flow completes with a "Auth Successful" message, but commits cannot be retrieved

**Additional context**
Only applies to `wego ui run`; does not happen when doing `npm start` for dev work

### PR DESCRIPTION
**Pull request by jpellizzari**
Closes #812 

The `gitops ui run` command wan't using the latest application handler where we have all of our auth middleware. This would have been missed when testing with the API server and dev frontend.

### CODE REVIEW

**Review by luizbafilho — APPROVED** [review]
it worked as expected

File: cmd/gitops/ui/run/cmd.go [hunk 1]
```diff
@@ -12,13 +12,13 @@ import (
 	"syscall"
 	"time"
 
-	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
+	"github.com/go-logr/zapr"
```
Comment (jpellizzari) [inline cmd/gitops/ui/run/cmd.go:15]:
```suggestion
	"github.com/go-logr/zapr/v2"
```
