### PR TITLE
Don't display error section if ImagePolicy not found for ImageRepo

### LINKED ISSUE #3356: Image Policy details fail to show when Policy name is different from Repository name
**Describe the bug**
Currently, if the Policy object is named differently from the Repository object, the Policy details fail to show (normally shown below the Repository details). The UI should not rely on names for associating objects, a user may have an image repository named `foo` and an image policy named `bar` that references `foo`.

**Environment**

- Weave-Gitops Version 0.16.0
- Flux Version 0.38
- Kubernetes version (any supported by Flux)

**To Reproduce**

1. Add the following manifests to your repo
   ```
   apiVersion: image.toolkit.fluxcd.io/v1beta1
   kind: ImageRepository
   metadata:
     name: podinfo-repo
     namespace: default
   spec:
     image: ghcr.io/stefanprodan/podinfo
     interval: 1h
   ---
   apiVersion: image.toolkit.fluxcd.io/v1beta1
   kind: ImagePolicy
   metadata:
     name: podinfo-policy
     namespace: default
   spec:
     imageRepositoryRef:
       name: podinfo-repo
     policy:
       semver:
         range: 5.0.x
   ```
2. Go to `IMAGE AUTOMATION` section and click on the `IMAGE REPOSITORIES` tab
3. Click on the link to the `podinfo-repo` Image Repository

**Expected behavior**

Ideally the details of the Policy object that references the Repository selected are shown. If this is not performant, then perhaps we should add a new tab for Policies, show a list of Policies there and show the Repository object details along with the Policy object details.

**Actual Behavior**
An error shown indicating no Policy exists with that name.

**Additional Context (screenshots, logs, etc)**

### PR DESCRIPTION
**Pull request by TheGostKasper**
Closes #3356 ,
As Image Policy details fail to show when Policy name is different from Repository name so we agreed to hide `Policy` section in case it's not found .

We @yiannistri @MostafaMegahid and i agreed to remove the `Policy` section from `ImageRepo details` and add a new tab to Image Automation for `Image Policies` .

- Image Policy List will display the basic info of the Policy and `ImageRepoRef` which will navigate to ImageRepo details page 
- Image repository details page will have a `Link button` navigate to `ImagePolicies` filtered by imageRepo name 

https://user-images.githubusercontent.com/4614360/217048593-c4b55c74-2926-40dd-8849-7fabdf72d4bb.mp4

### CODE REVIEW

File: ui/components/ImageAutomation/policies/ImagePoliciesTable.tsx [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+          {
+            label: "Order/Range",
+            value: ({ imagePolicy }: { imagePolicy: ImgPolicy }) =>
+              imagePolicy?.value || "",
+          },
+          {
+            label: "Image Repository",
+            value: ({ imageRepositoryRef, namespace, clusterName }) => (
+              <Link
+                to={formatURL(V2Routes.ImageAutomationRepositoriesDetails, {
```
Comment (joshri) [inline ui/components/ImageAutomation/policies/ImagePoliciesTable.tsx:59]: Just want to make sure this is supposed to be `Repositories` and not `Repository` in `ImageAutomationRepositoriesDetails`

File: ui/lib/objects.ts [hunk 2]
```diff
@@ -315,6 +319,26 @@ export class ImageUpdateAutomation extends FluxObject {
     return this.obj?.status?.lastAutomationRunTime || "";
   }
 }
+export class ImagePolicy extends ImageUpdateAutomation {
+  get imagePolicy(): ImgPolicy {
+    const { policy } = this.obj.spec;
```
Comment (joshri) [inline ui/lib/objects.ts:324]: `obj` is always defined?

File: ui/lib/objects.ts [hunk 3]
```diff
@@ -315,6 +319,26 @@ export class ImageUpdateAutomation extends FluxObject {
...
+        value: (val as string) || "",
+      };
+    }
+    return {
+      type: "",
+      value: "",
+    };
+  }
+  get imageRepositoryRef(): string {
+    return this.obj.spec?.imageRepositoryRef?.name || "";
```
Comment (joshri) [inline ui/lib/objects.ts:339]: same here - want to make sure we're handling the *classic* undefined case

**Review by joshri — APPROVED** [review]

**Review by jpellizzari — APPROVED** [review]
